compile:
	npx hardhat compile

deploy:
	npx hardhat run ignition/modules/Insure.ts --network lineaSepolia

verify:
	npx hardhat verify --network lineaSepolia 0x47B6DcD48414B9c4B42311DaB05DF17E9827Dd3b